#!/usr/bin/env zsh

iptables --flush
iptables --delete-chain KNOCKING
iptables --delete-chain PASSED
iptables --delete-chain REJECTLOG
iptables --delete-chain GATE1
iptables --delete-chain GATE2
iptables --delete-chain GATE3