#!/usr/bin/env bash

if [[ $# -ne 1 ]] || [[ ! $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
	echo "Usage: $0 IP.ADD.RE.SS"
else
	# Remove all rules and chains
	iptables --flush
	iptables --delete-chain

	# Allow all traffic on the loopback interface
	iptables -A INPUT -i lo -j ACCEPT
	iptables -A OUTPUT -o lo -j ACCEPT

	# Allow all established connections to continue to work
	iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

	# Allow web traffic
	iptables -A INPUT -p tcp --dport 80 -j ACCEPT
	iptables -A INPUT -p tcp --dport 443 -j ACCEPT

	# Drop everything else
	iptables -A INPUT -j DROP
	
	# Whitelist an ip address on port 22
	iptables -A INPUT -s $1/32 -p tcp -m tcp --dport 22 -j ACCEPT
	
	if [[ -f /etc/sysconfig/iptables ]]; then
		cp /etc/sysconfig/iptables /etc/sysconfig/iptables.old
		iptables-save > /etc/sysconfig/iptables
		echo "Rules saved to disk"
	elif [[ -f /etc/iptables/iptables.rules ]]; then
		cp /etc/iptables/iptables.rules /etc/iptables/iptables.rules.old
		iptables-save > /etc/iptables/iptables.rules
		echo "Rules saved to disk"
	else
		echo "You will need to manually save rules to disk"
	fi
fi