#!/usr/bin/env zsh

# Delete existing chains and rules
./blank-slate-iptables

# Loopback traffic needs to work
iptables -A INPUT -i lo -j ACCEPT

# Allow existing open connections and all outgoing traffic
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -j ACCEPT

# Set up a REJECT logging rule called REJECTLOG
iptables -N REJECTLOG
iptables -A REJECTLOG -j LOG --log-level debug --log-tcp-sequence --log-tcp-options --log-ip-options -m limit --limit 3/s --limit-burst 8 --log-prefix "REJECT "
iptables -A REJECTLOG -p tcp -j REJECT --reject-with tcp-reset
iptables -A REJECTLOG -j REJECT

# Set up the INPUT rules to allow connections on the specified ports only
iptables -A INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -m state --state NEW -p tcp --dport 443 -j ACCEPT
iptables -A INPUT -j REJECTLOG