#!/usr/bin/env zsh

if [[ $# -ne 2 ]]; then echo "Usage: $0 /path/to/update/flag/file /path/to/update/config/file.conf"; return; fi

update_flag_file=$1
config_file=$2

if [[ ! -f $update_flag_file ]]; then return 1; fi
if [[ ! -f $config_file ]]; then echo "The specified config file does not exist:" $config_file; return 1; fi

source $HOME/shell-scripts/sysadmin/user-utilities/user-utilities

function update-and-restart-server() {
	cd /home/$1/$2
	# In combination with the `lock` command executable binaries are no longer executable
	# Checkout to reset their permissions and allow a `git pull`
	git checkout .
	if [[ `git pull` != 'Already up-to-date.' ]]; then
		if [[ "$3" == "go" ]]; then
			# Break this out into its own if block to satisfy old-ass versions of zsh
			if ! go build; then
				echo 'Error: Could not `go build`.'
				return 1
			fi
		fi
		lock $1
		systemctl restart $1.service
	else
		echo 'Nothing to do for' $1
	fi
}

rm $update_flag_file

#Each line of the configuration file is in the format:
#USER DIRECTORY-OF-REPO

#Example:
#username relative/path/to/repo
#Which expands to /home/username/relative/path/to/repo

while IFS='' read -r line || [[ -n "$line" ]]; do
	eval "update-and-restart-server $line"
done < $config_file

unset update_flag_file config_file