#!/usr/bin/env zsh

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 /PATH/TO/CONFIG/FILE"
	echo "Each line in the configuration file is formatted:"
	echo "EMAIL DOMAIN [SUBDOMAIN]"
	return 1
fi

config_file=$1

if [[ ! -f $config_file ]]; then echo "The specified config file does not exist:" $config_file; return 1; fi

source /root/shell-scripts/sysadmin/create-letsencrypt-cert

while IFS='' read -r line || [[ -n "$line" ]]; do
	eval "create-letsencrypt-cert $line"
done < $config_file

unset config_file