#!/usr/bin/env zsh

if [[ $# -ne 1 ]]; then echo "Usage: $0 /path/to/update/file.conf"; return; fi

function update-and-restart-server() {
	cd /home/$1/$2
	if [[ `git pull` != 'Already up-to-date.' ]]; then
		if [[ "$3" == "go" ]]; then
			sudo -S -u $1 -i zsh -l -c "export GOPATH=/home/$1/go && cd $2 && go build"
		fi
		systemctl restart $1.service
	else
		echo 'Nothing to do for' $1
	fi
}

update_file=$1

if [[ -f $update_file ]]; then
#	rm $update_file
	
	#/root/sites-to-update.txt lines are in the format "USER DIRECTORY-OF-REPO"
	while IFS='' read -r line || [[ -n "$line" ]]; do
		eval "update-and-restart-server $line"
	done < /root/sites-to-update.txt
else
	echo "The specified config file does not exist:" $update_file
	return 1
fi

unset update_file