#!/usr/bin/env zsh

function update-and-restart-server() {
	cd /home/$1/$2
	if [[ `git pull` != 'Already up-to-date.' ]]; then
		systemctl restart $1.service
	else
		echo 'Nothing to do for' $1
	fi
}

update_file=$1

if [[ -f $update_file ]]; then
	rm $update_file
	
	#/root/sites-to-update.txt lines are in the format "USER DIRECTORY-OF-REPO"
	while IFS='' read -r line || [[ -n "$line" ]]; do
		eval "update-and-restart-server $line"
	done < /root/sites-to-update.txt
fi

unset update_file