#!/usr/bin/env zsh

if [[ $# -ne 1 ]]; then echo "Usage: $0 /path/to/whitelist/file"; return; fi

whitelist_file=$1

if [[ ! -f $whitelist_file ]]; then return; fi

whitelist_contents=`cat $whitelist_file`

if [[ ! "$whitelist_contents" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then return; fi

iptables -I INPUT -p tcp -m tcp -s $whitelist_contents --dport 22 -j ACCEPT

sleep 30

iptables -D INPUT -p tcp -m tcp -s $whitelist_contents --dport 22 -j ACCEPT


unset whitelist_file whitelist_contents