#!/usr/bin/env bash

if [[ $# -ne 3 ]]; then
	echo "Usage: $0 'command with or without arguments' 'build command' file-extension-expression"
else
	command=$1
	build_command=$2
	file_extension_expression=\.${3}$

	echo && echo 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv'
	$build_command && ./$command
	echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' && echo && echo

	inotifywait --format "%f" -me close_write -q . | while read file
	do
		if [[ ! "$file" =~ $file_extension_expression ]]; then continue; fi
		echo 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv'
		$build_command && echo "File modified: $file. Running: $command" && ./$command
		echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' && echo && echo
	done
fi
