#!/usr/bin/env bash

if [[ $# -ne 2 ]]; then
	echo "Usage: $0 'command with or without arguments' file-extension-expression"
else
	command=$1
	file_extension_expression=\.${2}$

	echo && echo 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv'
	$command
	echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' && echo && echo

	inotifywait --format "%f" -me close_write -q . | while read file
	do
		if [[ ! "$file" =~ $file_extension_expression ]]; then continue; fi
		echo "File modified: $file. Running: $command" && $command
		echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' && echo && echo
	done
fi