#!/usr/bin/env bash

function todo() {
	if [[ ! -f $todo_file_path ]]; then echo "The Todo file either does not exist or has not been set with the todo-list command."; return; fi
	if [[ $# -gt 0 ]]; then
		temporary_todo_file=/tmp/delete-me-temporary-todo-file.txt
		echo '*' $@ > $temporary_todo_file
		cat $todo_file_path >> $temporary_todo_file
		mv $temporary_todo_file $todo_file_path
		unset temporary_todo_file
	else
		todo-number 1
	fi
}

function todo-number() {
	if [[ $# -ne 1 ]]; then echo "Usage: $0 [index of todo]"; return; fi
	sed -n "${1}p" $todo_file_path
	unset todo_index
}

function todo-remove() {
	if [[ $# -ne 1 ]]; then echo "Usage: $0 [index of todo]"; return; fi
	todo-number $@
	echo "Proceed? (Y/n)"
	read proceed
	if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
		todo_index=1
		if [[ $# -eq 1 ]]; then todo_index=$1; fi
		sed -i "${todo_index}d" $todo_file_path
		unset todo_index
	fi
	unset proceed
}

function todone() {
	if [[ $# -gt 1 ]]; then echo "Too many arguments. Usage: $0 [index of todo]"; return; fi
	todo_index=1
	if [[ $# -eq 1 ]]; then todo_index=$1; fi
	done_todo=`sed -n "${todo_index}p" $todo_file_path`
	echo "Complete:" $done_todo
	echo $done_todo >> $todo_file_path
	sed -i "${todo_index}d" $todo_file_path
	unset todo_index done_todo
}

function todo-list() {
	if [[ $# -ne 1 ]]; then
		if [[ "$todo_file_path" == "" ]]; then
			echo "No todo list selected. To select one, use: $0 name-of-todo-list"
		else
			echo $todo_file_path
		fi
		return;
	fi
	if [[ "$todo_file_extension" == "" ]]; then todo_file_extension="org"; fi
	todo_file_path="$todo_directory/$1.$todo_file_extension"
	# Note: -f checks full paths only
	if [[ ! -f $todo_file_path ]]; then
		echo "No todo list exists at: $todo_file_path";
		echo "Create one? (Y/n)"
		read proceed
		if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
			touch $todo_file_path
			todo-list $1
			todo DONE
		else
			unset todo_file_path
		fi
		unset proceed
		return;
	else
		todo
	fi
}

function todo-lists() {
	if [[ "$todo_file_extension" == "" ]]; then todo_file_extension="org"; fi
	ls $todo_directory | sed s@\.${todo_file_extension}@@g
}

function todo-edit() {
	eval "$EDITOR $todo_file_path &"
}

function todos() {
	less $todo_file_path
}