#!/usr/bin/env bash

function todo() {
	if [[ ! -f $todo_file_path ]]; then echo "The Todo file either does not exist or has not been set with the todo-list command."; return; fi
	if [[ $# -gt 1 ]]; then echo "Too many arguments. Usage: $0 [index of todo]"; return; fi
	todo_index=1
	if [[ $# -eq 1 ]]; then todo_index=$1; fi
	sed -n "${todo_index}p" $todo_file_path
	unset todo_index
}

function todo-add() {
	temporary_todo_file=/tmp/delete-me-temporary-todo-file.txt
	echo '*' $@ > $temporary_todo_file
	cat $todo_file_path >> $temporary_todo_file
	mv $temporary_todo_file $todo_file_path
	unset temporary_todo_file
}

function todo-delete() {
	todo $@
	echo "Proceed? (Y/n)"
	read proceed
	if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
		sed -i "${todo_index}d" $todo_file_path
	fi
	unset proceed
}

function todone() {
	if [[ $# -gt 1 ]]; then echo "Too many arguments. Usage: $0 [index of todo]"; return; fi
	todo_index=1
	if [[ $# -eq 1 ]]; then todo_index=$1; fi
	done_todo=`sed -n "${todo_index}p" $todo_file_path`
	echo "Complete:" $done_todo
	echo $done_todo >> $todo_file_path
	sed -i "${todo_index}d" $todo_file_path
	unset todo_index done_todo
}

function todo-list() {
	if [[ $# -ne 1 ]]; then echo "Usage: $0 which-todo-list"; return; fi
	if [[ "$todo_file_extension" == "" ]]; then todo_file_extension="org"; fi
	todo_file_path="$todo_directory/$1.$todo_file_extension"
	# Note: -f checks full paths only
	if [[ ! -f $todo_file_path ]]; then
		echo "No todo list exists at: $todo_file_path";
		unset todo_file_path
		return;
	else
		todo
	fi
}